(function(){"use strict";
var P=CJCData.profile,t=CJCData.t.bind(CJCData),esc=CJCData.escapeHtml,projects=[],articles=[],filter="all",copy={en:{about:"About me",aboutLead:"A clear portrait behind the interface.",education:"Education",skills:"Core technology",courses:"Courses",experience:"Experience",projects:"Projects",articles:"Articles",certificates:"Certificates",contact:"Get in touch",send:"Send message",sending:"Sending…",sent:"Thanks — your message is on its way.",retry:"Try again",empty:"Nothing here yet.",open:"Open project",read:"Read article",gallery:"Theme gallery"},zh:{about:"关于我",aboutLead:"界面背后，一个清晰而真实的自我介绍。",education:"教育背景",skills:"核心技术",courses:"核心课程",experience:"实习经历",projects:"项目作品",articles:"文章博客",certificates:"证书荣誉",contact:"联系我",send:"发送消息",sending:"发送中…",sent:"感谢，消息已送达。",retry:"重试",empty:"暂无内容。",open:"查看项目",read:"阅读文章",gallery:"主题画廊"}};
function L(){return copy[CJCData.lang()]||copy.en}function title(k){return t(P.ui[k])||L()[k]}
function head(k,n,lead){return '<div class="heading"><span class="num">'+String(n).padStart(2,"0")+' / 09</span><div><h2>'+esc(L()[k]||title(k))+'</h2>'+(lead?'<p class="muted">'+esc(lead)+'</p>':'')+'</div></div>'}
function staticSections(){var x=L();document.getElementById("nav").innerHTML=[['about',x.about],['education',x.education],['skills',x.skills],['courses',x.courses],['experience',x.experience],['projects',x.projects],['articles',x.articles],['contact',x.contact]].map(function(i){return '<a href="#'+i[0]+'">'+esc(i[1])+'</a>'}).join("");
var hero='<section class="hero" id="top"><div class="wrap"><div class="hero-card glass"><div><div class="eyebrow">'+esc(t(P.greeting))+'</div><h1>'+esc(t(P.name))+'</h1><p class="hero-role">'+esc(t(P.role))+'</p><p class="hero-copy">'+esc(t(P.headline))+'</p><p class="hero-sub">'+esc(t(P.title))+' · '+esc(t(P.location))+'</p><div class="actions"><a class="button primary" href="'+esc(t(P.cv))+'" download>'+esc(t(P.ui.download_cv))+'</a><a class="button" href="'+esc(P.contact.github)+'" target="_blank" rel="noopener">GitHub ↗</a></div></div><img class="avatar" src="'+esc(P.avatar)+'" alt="'+esc(t(P.name))+'" decoding="async"></div></div></section>';
var about='<section id="about"><div class="wrap">'+head("about",1,x.aboutLead)+'<div class="bio glass"><img src="'+esc(P.photos&&P.photos.campus||P.avatar)+'" alt="'+esc(t(P.name))+'" loading="lazy" decoding="async"><div class="bio-copy">'+P.bio.map(function(b){return '<p>'+esc(t(b))+'</p>'}).join("")+'<p class="muted">⌖ '+esc(t(P.location))+'</p></div></div></div></section>';
var edu='<section id="education"><div class="wrap">'+head("education",2)+'<div class="grid two">'+P.education.map(function(e){return '<article class="card glass"><div class="kicker">'+esc(e.period)+'</div><h3>'+esc(t(e.school))+'</h3><p class="muted"><strong>'+esc(t(e.degree))+'</strong><br>'+esc(t(e.note))+'</p></article>'}).join("")+'</div></div></section>';
var skills='<section id="skills"><div class="wrap">'+head("skills",3)+'<div class="skills glass">'+(P.skillTags||[]).map(function(s){return '<span class="chip">'+esc(s)+'</span>'}).join("")+'</div></div></section>';
var courses='<section id="courses"><div class="wrap">'+head("courses",4)+'<div class="grid">'+P.courses.map(function(c){return '<article class="card glass"><div class="kicker">'+esc(c.icon.replace("fa-",""))+'</div><h3>'+esc(t(c.title))+'</h3><p class="muted">'+esc(t(c.desc))+'</p></article>'}).join("")+'</div></div></section>';
var exp='<section id="experience"><div class="wrap">'+head("experience",5)+'<div class="card glass">'+P.experience.map(function(e){return '<div class="kicker">'+esc(e.period)+' · '+esc(t(e.company))+'</div><h3>'+esc(t(e.role))+'</h3><p class="muted">'+esc(t(e.summary))+'</p><ul>'+e.bullets.map(function(b){return '<li>'+esc(t(b))+'</li>'}).join("")+'</ul>'}).join("")+'</div></div></section>';
var cert='<section id="certificates"><div class="wrap">'+head("certificates",8)+'<div class="grid two">'+P.certificates.map(function(c){return '<article class="cert glass"><img src="'+esc(c.image)+'" alt="'+esc(t(c.title))+'" loading="lazy" decoding="async"><div class="cert-copy"><div class="kicker">'+esc(t(c.tag))+' · '+esc(t(c.date))+'</div><h3>'+esc(t(c.title))+'</h3><p class="muted">'+esc(t(c.desc))+'</p></div></article>'}).join("")+'</div></div></section>';
var contact='<section id="contact"><div class="wrap">'+head("contact",9)+'<div class="contact-grid glass"><div class="contact-links"><a href="mailto:'+esc(P.contact.email)+'"><span>Email</span><span>'+esc(P.contact.email)+'</span></a><a href="'+esc(P.contact.phoneHref)+'"><span>Phone</span><span>'+esc(P.contact.phone)+'</span></a><a href="'+esc(P.contact.github)+'" target="_blank" rel="noopener"><span>GitHub</span><span>@'+esc(P.contact.githubUser)+'</span></a><a href="'+esc(P.contact.wechatQrPage)+'"><span>WeChat</span><span>QR</span></a></div><form id="contact-form"><label for="cf-name">'+esc(t(P.ui.name_placeholder))+'</label><input id="cf-name" name="name" autocomplete="name" required><label for="cf-email">'+esc(t(P.ui.email_placeholder))+'</label><input id="cf-email" type="email" name="email" autocomplete="email" required><label for="cf-message">'+esc(t(P.ui.msg_placeholder))+'</label><textarea id="cf-message" name="message" required></textarea><button class="button primary" type="submit">'+esc(L().send)+'</button><p id="cf-status" role="status" aria-live="polite"></p></form></div></div></section>';
document.getElementById("main").innerHTML=hero+about+edu+skills+courses+exp+'<section id="projects"><div class="wrap">'+head("projects",6)+'<div id="project-list" class="grid"><div class="state">'+esc(t(P.ui.loading_projects))+'</div></div></div></section>'+'<section id="articles"><div class="wrap">'+head("articles",7)+'<div class="filters" id="filters"></div><div id="article-list" class="grid"><div class="state">'+esc(t(P.ui.loading_articles))+'</div></div></div></section>'+cert+contact;document.getElementById("foot-note").textContent=t(P.ui.footer_desc);document.getElementById("foot-links").innerHTML='<a href="/themes.html">'+esc(L().gallery)+'</a> · <a href="'+esc(P.icpUrl)+'" target="_blank" rel="noopener">'+esc(P.icp)+'</a>';wireForm()}
function card(item,kind){var isP=kind==="project",cover=item.cover_image||"/index_page/img/blogs/1.jpg",label=isP?L().open:L().read;return '<a class="'+(isP?"project-card":"article-card")+' glass" href="'+esc(item.detailHref)+'"><div class="cover"><img src="'+esc(cover)+'" alt="'+esc(item.localTitle())+'" loading="lazy" decoding="async" onerror="this.onerror=null;this.src=\'/index_page/img/blogs/1.jpg\'"></div><div class="card-body"><div class="card-meta">'+esc(isP?(item.tech_stack||title("tech_stack")):((item.category||"ARCHIVE")+" · "+item.dateText()))+'</div><h3>'+esc(item.localTitle())+'</h3><p class="muted">'+esc(item.localSummary()||"")+'</p><span class="card-link">'+esc(label)+' ↗</span></div></a>'}
function renderDynamic(){var p=document.getElementById("project-list"),a=document.getElementById("article-list");p.innerHTML=projects.length?projects.map(function(x){return card(x,"project")}).join(""):'<div class="state glass">'+esc(L().empty)+'</div>';var visible=CJCData.filterArticles(articles,filter);document.getElementById("filters").innerHTML=P.articleFilters.map(function(f){return '<button type="button" data-filter="'+esc(f.key)+'" class="'+(filter===f.key?"active":"")+'" aria-pressed="'+(filter===f.key)+'">'+esc(t(f.label))+'</button>'}).join("");a.innerHTML=visible.length?visible.map(function(x){return card(x,"article")}).join(""):'<div class="state glass">'+esc(L().empty)+'</div>';document.querySelectorAll("[data-filter]").forEach(function(b){b.onclick=function(){filter=b.dataset.filter;renderDynamic()}})}
function wireForm(){var f=document.getElementById("contact-form");if(!f)return;f.onsubmit=async function(e){e.preventDefault();var s=document.getElementById("cf-status"),b=f.querySelector("button");b.disabled=true;s.textContent=L().sending;try{var r=await CJCData.sendContact({name:f.name.value,email:f.email.value,message:f.message.value});s.textContent=r.message||L().sent;f.reset()}catch(err){s.textContent=err.message||"Error"}finally{b.disabled=false}}}
async function load(){try{projects=await CJCData.fetchProjects()}catch(e){projects=[]}try{articles=await CJCData.fetchArticles()}catch(e){articles=[]}renderDynamic()}
document.addEventListener("DOMContentLoaded",function(){CJCData.setTheme(window.THEME_ID);staticSections();CJCData.mountSwitcher({accent:"#8874ff"});CJCData.onLang(function(){staticSections();renderDynamic()});load()})})();
