(function(){"use strict";
var P=CJCData.profile,t=CJCData.t.bind(CJCData),esc=CJCData.escapeHtml,projects=[],articles=[],filter="all",stack=["home"],history=[],hi=0;
var S={en:{about:"about",education:"education",skills:"skills",courses:"courses",experience:"experience",projects:"projects",articles:"articles",certs:"certificates",contact:"contact",empty:"no records",sent:"message sent",sending:"sending…"},zh:{about:"关于我",education:"教育背景",skills:"核心技术",courses:"核心课程",experience:"实习经历",projects:"项目作品",articles:"文章博客",certs:"证书荣誉",contact:"联系我",empty:"暂无记录",sent:"消息已发送",sending:"发送中…"}};
function L(){return S[CJCData.lang()]||S.en}function sh(){return '<span class="promptline">visitor@caijiechao:<span class="path">~</span>$</span>'}function sec(id,body){return '<section class="block" id="'+id+'"><h2>'+sh()+' cat '+id+'</h2>'+body+'</section>'}
function about(){return '<div class="line"><img class="cover" src="'+esc(P.avatar)+'" alt="'+esc(t(P.name))+'" loading="lazy"><b>'+esc(t(P.name))+'</b> <span class="dim">— '+esc(t(P.role))+' @ '+esc(t(P.location))+'</span></div>'+P.bio.map(function(b){return '<p class="dim">'+esc(t(b))+'</p>'}).join("")}
function education(){return P.education.map(function(e){return '<div class="kv"><span class="amber">['+esc(e.period)+']</span><h3>'+esc(t(e.school))+'</h3><p>'+esc(t(e.degree))+' · '+esc(t(e.note))+'</p></div>'}).join("")}
function skills(){return '<div class="tags">'+P.skillTags.map(function(x){return '<span class="tag">'+esc(x)+'</span>'}).join("")+'</div>'}
function courses(){return '<div class="list">'+P.courses.map(function(c){return '<div class="kv"><h3>'+esc(t(c.title))+'</h3><p>'+esc(t(c.desc))+'</p></div>'}).join("")+'</div>'}
function experience(){return P.experience.map(function(e){return '<div class="kv"><span class="amber">['+esc(e.period)+']</span><h3>'+esc(t(e.role))+' @ '+esc(t(e.company))+'</h3><p>'+esc(t(e.summary))+'</p><ul>'+e.bullets.map(function(b){return '<li>'+esc(t(b))+'</li>'}).join("")+'</ul></div>'}).join("")}
function certs(){return '<div class="certs">'+P.certificates.map(function(c){return '<article class="cert"><img src="'+esc(c.image)+'" alt="'+esc(t(c.title))+'" loading="lazy"><div><b>'+esc(t(c.title))+'</b><p class="dim">'+esc(t(c.tag))+' · '+esc(t(c.date))+'</p></div></article>'}).join("")+'</div>'}
function contact(){return '<div class="contact"><div><a href="mailto:'+esc(P.contact.email)+'"><span>email</span><span>'+esc(P.contact.email)+'</span></a><a href="'+esc(P.contact.phoneHref)+'"><span>phone</span><span>'+esc(P.contact.phone)+'</span></a><a href="'+esc(P.contact.github)+'" target="_blank" rel="noopener"><span>github</span><span>@'+esc(P.contact.githubUser)+'</span></a><a href="'+esc(P.contact.wechatQrPage)+'"><span>wechat</span><span>QR ↗</span></a></div><form id="contact-form"><label for="c-name">name</label><input id="c-name" name="name" required><label for="c-email">email</label><input id="c-email" type="email" name="email" required><label for="c-msg">message</label><textarea id="c-msg" name="message" required></textarea><button type="submit">./send</button><p id="status" role="status" aria-live="polite"></p></form></div>'}
function row(x,i,k){return '<a class="row cmd-link" href="'+esc(x.detailHref)+'"><span class="idx">['+(i+1)+']</span><span><strong>'+esc(x.localTitle())+'</strong><small class="card-copy">'+esc(x.localSummary()||"")+'</small></span><span class="date">'+esc(k==="project"?(x.tech_stack||""):x.dateText())+'</span></a>'}
function projectsView(){return projects.length?'<div class="list">'+projects.map(function(x,i){return row(x,i,"project")}).join("")+'</div>':'<p class="dim">'+L().empty+'</p>'}
function articlesView(){var visible=CJCData.filterArticles(articles,filter);return '<div class="filters">'+P.articleFilters.map(function(f){return '<button class="openbtn" data-filter="'+esc(f.key)+'" type="button">'+esc(t(f.label))+'</button>'}).join(" ")+'</div>'+(visible.length?'<div class="list">'+visible.map(function(x,i){return row(x,i,"article")}).join("")+'</div>':'<p class="dim">'+L().empty+'</p>')}
function home(){var menu=["about","education","skills","courses","experience","projects","articles","certs","contact"];return '<pre class="ascii" aria-label="Cai Jiechao">C A I   J I E C H A O\nterminal portfolio / 2026</pre><div class="line">'+sh()+' <b>'+esc(t(P.name))+'</b> <span class="dim">— '+esc(t(P.role))+' @ '+esc(t(P.location))+'</span></div><p class="dim">'+esc(t(P.bio[0]))+'</p><div class="menu">'+menu.map(function(id){return '<button type="button" data-cmd="'+id+'"><span class="green">'+esc(L()[id])+'</span><span class="command">cd ~/'+id+'</span></button>'}).join("")+'</div><p class="dim">'+sh()+' type <span class="green">help</span> · <span class="green">all</span> · <span class="green">theme</span></p>'}
function all(){return sec("about",about())+sec("education",education())+sec("skills",skills())+sec("courses",courses())+sec("experience",experience())+sec("projects",projectsView())+sec("articles",articlesView())+sec("certs",certs())+sec("contact",contact())}
function view(v){if(v==="home")return home();if(v==="all")return all();if(v==="about")return sec(v,about());if(v==="education")return sec(v,education());if(v==="skills")return sec(v,skills());if(v==="courses")return sec(v,courses());if(v==="experience")return sec(v,experience());if(v==="projects")return sec(v,projectsView());if(v==="articles")return sec(v,articlesView());if(v==="certs")return sec(v,certs());if(v==="contact")return sec(v,contact());if(v==="help")return '<div class="line green">'+sh()+' man cjc</div><p class="dim">about education skills courses experience projects articles certs contact · all · back · clear · lang · theme</p>';return home()}
function render(){document.getElementById("screen").innerHTML=view(stack[stack.length-1]);wire()}
function run(raw){var text=(raw||"").trim(),cmd=text.toLowerCase().split(/\s+/)[0];if(!cmd)return;history.push(text);hi=history.length;if(cmd==="theme"||cmd==="themes"){location.href="/themes.html";return}if(cmd==="lang"){CJCData.toggleLang();return}if(cmd==="back"||cmd==="b"||cmd===".."||cmd==="esc"){if(stack.length>1)stack.pop();render();return}if(cmd==="home"||cmd==="clear"||cmd==="cls"||cmd==="ls"){stack=["home"];render();return}if(cmd==="all"){stack.push("all");render();return}var map={about:"about",education:"education",edu:"education",skills:"skills",courses:"courses",experience:"experience",exp:"experience",projects:"projects",project:"projects",articles:"articles",article:"articles",certs:"certs",certificates:"certs",contact:"contact",help:"help",man:"help"};if(map[cmd]){stack.push(map[cmd]);render();return}document.getElementById("screen").insertAdjacentHTML("beforeend",'<p class="amber">command not found: '+esc(cmd)+' — type help</p>')}
function wire(){document.querySelectorAll("[data-cmd]").forEach(function(b){b.onclick=function(){stack.push(b.dataset.cmd);render()}});document.querySelectorAll("[data-filter]").forEach(function(b){b.onclick=function(){filter=b.dataset.filter;render()}});var f=document.getElementById("contact-form");if(f)f.onsubmit=async function(e){e.preventDefault();var s=document.getElementById("status"),b=f.querySelector("button");b.disabled=true;s.textContent=L().sending;try{var r=await CJCData.sendContact({name:f.name.value,email:f.email.value,message:f.message.value});s.textContent=r.message||L().sent;f.reset()}catch(err){s.textContent=err.message||"error"}finally{b.disabled=false}}}
async function load(){try{projects=await CJCData.fetchProjects()}catch(e){}try{articles=await CJCData.fetchArticles()}catch(e){}render()}
document.addEventListener("DOMContentLoaded",function(){CJCData.setTheme(window.THEME_ID);var input=document.getElementById("command");document.getElementById("lang").onclick=function(){CJCData.toggleLang()};document.getElementById("command-form").onsubmit=function(e){e.preventDefault();run(input.value);input.value=""};input.onkeydown=function(e){if(e.key==="ArrowUp"){hi=Math.max(0,hi-1);input.value=history[hi]||"";e.preventDefault()}else if(e.key==="ArrowDown"){hi=Math.min(history.length,hi+1);input.value=history[hi]||"";e.preventDefault()}else if(e.key==="Escape"&&stack.length>1){stack.pop();render()}};CJCData.onLang(render);render();load()})})();
